In [1]:
import numpy as np

In [2]:
l=[40.2,42.3,39.2,37.1,45.3]
l

[40.2, 42.3, 39.2, 37.1, 45.3]

In [3]:
l1=np.zeros([10,10])
l1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
t=np.zeros([10,10])
t2=np.zeros([10,10])
sum=0.01
for i in range(0,10):
    #sum+=0.01
    for j in range (0,10):
        t[i][j]=sum+t[i][j]
        sum+=0.01
t

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [21]:
t=np.array(l)
t*9/5+32


array([104.36, 108.14, 102.56,  98.78, 113.54])

In [6]:
np.array([[22,222,2222],[33,333,3333],[44,444,4444]])

array([[  22,  222, 2222],
       [  33,  333, 3333],
       [  44,  444, 4444]])

In [9]:
l=[2,3,4]

In [11]:
l1=[1,2,3]

In [12]:
l2=[6,2,2]

In [16]:
np.array([l,l1,l2])

array([['we', 'love', 'mcu'],
       ['real', 'madrid', 'sucks'],
       ['manish', 'pai', 'aande']], dtype='<U6')

In [17]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [26]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
np.ones(3)

array([1., 1., 1.])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
np.linspace(0,10,2)

array([ 0., 10.])

In [35]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(0,10,78)

array([ 0.        ,  0.12987013,  0.25974026,  0.38961039,  0.51948052,
        0.64935065,  0.77922078,  0.90909091,  1.03896104,  1.16883117,
        1.2987013 ,  1.42857143,  1.55844156,  1.68831169,  1.81818182,
        1.94805195,  2.07792208,  2.20779221,  2.33766234,  2.46753247,
        2.5974026 ,  2.72727273,  2.85714286,  2.98701299,  3.11688312,
        3.24675325,  3.37662338,  3.50649351,  3.63636364,  3.76623377,
        3.8961039 ,  4.02597403,  4.15584416,  4.28571429,  4.41558442,
        4.54545455,  4.67532468,  4.80519481,  4.93506494,  5.06493506,
        5.19480519,  5.32467532,  5.45454545,  5.58441558,  5.71428571,
        5.84415584,  5.97402597,  6.1038961 ,  6.23376623,  6.36363636,
        6.49350649,  6.62337662,  6.75324675,  6.88311688,  7.01298701,
        7.14285714,  7.27272727,  7.4025974 ,  7.53246753,  7.66233766,
        7.79220779,  7.92207792,  8.05194805,  8.18181818,  8.31168831,
        8.44155844,  8.57142857,  8.7012987 ,  8.83116883,  8.96

In [38]:
nx=2

In [39]:
ny=3

In [40]:
x=np.linspace(0,10,2)

In [41]:
y=np.linspace(0,10,ny)

In [42]:
xy,yy=np.meshgrid(x,y)

In [43]:
xy

array([[ 0., 10.],
       [ 0., 10.],
       [ 0., 10.]])

In [44]:
yy

array([[ 0.,  0.],
       [ 5.,  5.],
       [10., 10.]])

In [45]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
import random

In [49]:
random.randint(0,10)

3

In [50]:
np.random.rand(2)

array([0.82642599, 0.48084993])

In [51]:
np.random.rand(5,5)

array([[0.70840809, 0.97590081, 0.1424763 , 0.76312465, 0.71398878],
       [0.55996582, 0.35199487, 0.17352755, 0.37405937, 0.39201904],
       [0.15164067, 0.23873919, 0.24141988, 0.95366642, 0.46497482],
       [0.75412601, 0.80483535, 0.42974931, 0.84238374, 0.38284459],
       [0.67453617, 0.02177776, 0.85672025, 0.41579802, 0.99277707]])

In [52]:
np.random.randn(5)

array([ 0.01004042, -0.90073308,  0.90471071, -0.63828775, -1.36534043])

In [55]:
np.random.randn(5,5)#standard deviation rand number

array([[-0.48116767,  1.320743  , -0.52635699, -0.75585315,  0.6020204 ],
       [ 1.74682305, -0.66285277,  1.33012966,  0.98578038,  0.61216709],
       [ 0.55898626, -1.24382061, -0.3770456 , -0.57163305, -0.26501605],
       [-1.23576356,  0.66839671,  0.97906033, -0.99231484, -0.24998304],
       [-1.32168976,  1.39179325, -0.30192131,  0.28059806, -0.59756997]])

In [56]:
np.random.randint(0,10)

3

In [57]:
np.random.randint(0,100,4)

array([75, 46, 21, 44])

In [60]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
ranarr


NameError: name 'ranarr' is not defined

In [62]:
arr


NameError: name 'arr' is not defined

In [63]:
arr=np.random.randint(0,100,19)

In [64]:
arr

array([43, 30, 69, 85, 13, 56, 70, 81,  6, 21, 61, 12, 82, 31, 93, 74,  3,
       36, 98])

In [65]:
arr.max()

98

In [66]:
arr.argmax()


18

In [67]:
arr.min()

3

In [68]:
arr.argmin()

16

In [71]:
arr=np.random.randint(0,100,7)

In [72]:
arr=np.random.randint(0,100,6)

In [73]:
arr.shape

(6,)

In [74]:
arr.reshape(2,3)

array([[99, 23, 16],
       [18, 20, 44]])

In [75]:
arr.reshape(3,2)

array([[99, 23],
       [16, 18],
       [20, 44]])

In [77]:
arr.reshape(3,2).shape

(3, 2)

In [84]:
a=np.array([1,24,66,23,19,"bihari"])

In [85]:
a.dtype

dtype('<U11')

In [80]:
ao=np.array([1,2,2,21,11,112,1123,1111,1111,12])

In [81]:
ao.shape

(10,)

In [82]:
ao.reshape(2,5).shape

(2, 5)

In [83]:
ao.reshape(2,5)

array([[   1,    2,    2,   21,   11],
       [ 112, 1123, 1111, 1111,   12]])

In [1]:
#numpy indexing and slicing

In [2]:
import numpy as np
l=[40.8,89.0,78,98.8]
c=np.array(l)

In [3]:
c[2]


78.0

In [7]:
c[3-4]

98.8

In [17]:
c[1:3]

array([89., 78.])

In [20]:
#broadcasting
c[1:3]=100#for making value 1,2 index equals to 100
c

array([ 40.8, 100. , 100. ,  98.8])

In [21]:
c>45#checking which vaue greatr45

array([False,  True,  True,  True])

In [22]:
#now for value greater 45
c[c>45]#gives the value greater 45

array([100. , 100. ,  98.8])

In [8]:
t=np.array([[3,4,5],[5,43,3],[0,3,0]])

In [9]:
t

array([[ 3,  4,  5],
       [ 5, 43,  3],
       [ 0,  3,  0]])

In [10]:
t[2][2]#indexing

0

In [13]:
t[1:3][1:3]#slicing

array([[0, 3, 0]])

In [19]:
t[1:3,0:2]

array([[ 5, 43],
       [ 0,  3]])

In [15]:
t[1:3,1:2]

array([[43],
       [ 3]])

In [16]:
t[0:2,0:3]

array([[ 3,  4,  5],
       [ 5, 43,  3]])

In [23]:
#numpy operation

In [24]:
import numpy as np

In [25]:
arr1=np.array([12,34,56,89.78,45.34])

In [26]:
arr2=np.array([11.1,54,72,11.890,89.11])

In [27]:
arr1-arr2

array([  0.9 , -20.  , -16.  ,  77.89, -43.77])

In [28]:
arr2+arr1

array([ 23.1 ,  88.  , 128.  , 101.67, 134.45])

In [29]:
arr1*arr2

array([ 133.2   , 1836.    , 4032.    , 1067.4842, 4040.2474])

In [30]:
arr1=np.append(arr1,[11.6])#adding extra element using python in array

In [31]:
arr1

array([12.  , 34.  , 56.  , 89.78, 45.34, 11.6 ])

In [32]:
#nan i.e when value cannot be adjust then not a number (nan) basically comes in case of the division by 0

In [33]:
#sqrt, log,max,min extra function
arr1=np.append(arr1,[34,67])

In [34]:
arr1


array([12.  , 34.  , 56.  , 89.78, 45.34, 11.6 , 34.  , 67.  ])

In [35]:
arr2

array([11.1 , 54.  , 72.  , 11.89, 89.11])

In [36]:
arr2-arr1

ValueError: operands could not be broadcast together with shapes (5,) (8,) 

In [37]:
arr1*arr2

ValueError: operands could not be broadcast together with shapes (8,) (5,) 

In [38]:
import pandas as pd

In [39]:
#install conda install 

#!pip install panda#net sholud be connect to install panda



In [40]:
#Series
import numpy as np

In [42]:
import pandas as pd

In [43]:
labels=['a','b','c']

In [44]:
my_list=([10,20,30])

In [45]:
arr=np.array([10,20,30])

In [46]:
d={'a':10,'b':20,'c':30}

In [57]:
#now for series using list

In [50]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

In [55]:
pd.Series(data=my_list,index=[1,2,3])

1    10
2    20
3    30
dtype: int64

In [56]:
pd.Series(data=my_list,index=[3,5,6])

3    10
5    20
6    30
dtype: int64

In [58]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [60]:
pd.Series(data=labels,index=[4,8,5])

4    a
8    b
5    c
dtype: object

In [61]:
pd.Series(data=d)

a    10
b    20
c    30
dtype: int64

In [63]:
pd.Series(data=d,index=[0,1,0])

0   NaN
1   NaN
0   NaN
dtype: float64