In [1]:
#define a function 
# a function must return a value in python , in c it return 0 
def sub(x,y):
    z=x-y
    return z


In [2]:
#For taking input 
x=int(input("Enter tge value"))
y=int(input("enter the value"))

Enter tge value4
enter the value7


In [3]:
def sub(x,y):
    z=x-y
    return z
a=int(input("Enter tge value"))
y=int(input("enter the value"))
#calling a function 
sub(a,y)

Enter tge value6
enter the value8


-2

In [7]:
#using a for loop
for i in range(2,100):
    print (i,end=" ")#end=" " to print in horizontal line
    #can also print in vertical by not writing the end=" "
# also write a list or array length in place of range(2,100)    

2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [13]:
#writing array length in place of range
import numpy as np
t=np.zeros([2,2])
t
for i in t:
    print(i)

[0. 0.]
[0. 0.]


In [14]:
#using while loop
a=3
while (a<9):# while a<9:
    print(a)
    a=a+2

3
5
7


In [15]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    for  j in range (1,4):# j last value will be last-1
        print(j)#end=" "for horizontal

1
2
3
1
2
3
1
2
3


In [16]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    for  j in range (1,4):# j last value will be last-1
        print(j,end=" ")#end=" "for horizontal

1 2 3 1 2 3 1 2 3 

In [17]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    for  j in range (1,4):# j last value will be last-1
        print(i,end=" ")

1 1 1 2 2 2 3 3 3 

In [18]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    print()#to go in line after for loop of j ends it value 
    for  j in range (1,4):# j last value will be last-1
        print(j,end=" ")#end=" "for horizontal


1 2 3 
1 2 3 
1 2 3 

In [20]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    print()#here it leave space after for loop of j ends
    for  j in range (1,4):# j last value will be last-1
        print(j)#end=" "for horizontal


1
2
3

1
2
3

1
2
3


In [22]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    print(end=" ")#it helps in spacing after the for loop of j ends 
    for  j in range (1,4):# j last value will be last-1
        print(i,end=" ")#end=" "for horizontal

 1 1 1  2 2 2  3 3 3 

In [23]:
#using for loop for 1,2,3 pattern
for i in range(1,4):#i i always in 1,3 i.e last-1 i.e 4-1=3
    print()#to go in line after for loop of j ends it value 
    for  j in range (1,4):# j last value will be last-1
        print(i,end=" ")#end=" "for horizontal


1 1 1 
2 2 2 
3 3 3 

In [25]:
#lamda function use i.e lambda function much easier to use consume less line then define function 
#s=lambda (no. of arguments) :(expression)
#print(s(value of argument i.e x))
s=lambda x:x*x*x
print(s(9))

729


In [26]:
#another exa,ple of lambda function

In [33]:
s=lambda x,y:x+y
x=int (input("enter value for x"))
a=int (input ("enter the value for y"))
print(s(x,a))
#print(lambda x,y:x+y(6,10)) can't define like this

enter value for x2
enter the value for y1
3


In [34]:
#import numpy library for use of the array
import numpy as np

In [41]:
#define a list
#list are just like arrays, declared in other language 
#list can uses different data type at same time i.e integer ,string as well as object
#list are mutable i.e that is it can be changed at any time
#list can be used to implement stack and queue
l=[1,4,67,89,'list','tomato']#one dimensional list
l


[1, 4, 67, 89, 'list', 'tomato']

In [39]:
l[5]#indexing  start from 0


'tomato'

In [43]:
#multi dimensional list
l1=['ram','sita',34.4,22,[l],['rohan', 'anaya']]
l1

['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya']]

In [47]:
#indexing of multidimensional
l1[2]

34.4

In [48]:
l1[4]

[[1, 4, 67, 89, 'list', 'tomato']]

In [53]:
l1[5]

['rohan', 'anaya']

In [54]:
l1[4][0]

[1, 4, 67, 89, 'list', 'tomato']

In [55]:
l1[4][0][1]#indexing of 4th elmnet of list

4

In [57]:
l1[5][1]

'anaya'

In [58]:
#adding element to  list append() & extend()
l1.append(3)#append() function adds the element at the last of the array or list
l1

['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya'],
 3]

In [67]:
l1.append('parul')# can append multiple items like l1.append(9,8,7,'pARUL')
l1

['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya'],
 3,
 'parul',
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul']

In [68]:
l1.append(l)#appending or adding the list to the list1
l1

['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya'],
 3,
 'parul',
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 [1, 4, 67, 89, 'list', 'tomato']]

['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya'],
 3,
 'parul',
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 [1, 4, 67, 89, 'list', 'tomato']]

In [72]:
#extending
l1.insert(13,3)
l1


['ram',
 'sita',
 34.4,
 22,
 [[1, 4, 67, 89, 'list', 'tomato']],
 ['rohan', 'anaya'],
 3,
 'parul',
 'parul',
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 0,
 [1, 4, 67, 89, 'list', 'tomato'],
 3,
 [1, 4, 67, 89, 'list', 'tomato'],
 'parul',
 [1, 4, 67, 89, 'list', 'tomato']]

In [73]:
l2=['parul','tanya','romania','peraie','caribean',5,7,l]
l2

['parul',
 'tanya',
 'romania',
 'peraie',
 'caribean',
 5,
 7,
 [1, 4, 67, 89, 'list', 'tomato']]

In [74]:
#use to insert at specific position i.e postion number then number or char want to add
l2.insert(1,'rahul')
l.insert(6,'brinjal')
l2

['parul',
 'rahul',
 'tanya',
 'romania',
 'peraie',
 'caribean',
 5,
 7,
 [1, 4, 67, 89, 'list', 'tomato', 'brinjal']]

In [75]:
print(l2,end=" ")

['parul', 'rahul', 'tanya', 'romania', 'peraie', 'caribean', 5, 7, [1, 4, 67, 89, 'list', 'tomato', 'brinjal']] 

l1.append((5,6))
print(l1,end=" ")

In [77]:
l1.append((5,6))
print(l1,end=" ")


['ram', 'sita', 34.4, 22, [[1, 4, 67, 89, 'list', 'tomato', 'brinjal']], ['rohan', 'anaya'], 3, 'parul', 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', 0, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 3, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], (5, 6)] 

In [84]:
for i in range(1,7):
    l1.append((i,i))
print(l1,end=" ")

['ram', 'sita', 34.4, 22, [[1, 4, 67, 89, 'list', 'tomato', 'brinjal']], ['rohan', 'anaya'], 3, 'parul', 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', 0, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 3, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], (5, 6), 1, 2, 3, 4, 5, 6, 'i', 'i', 'i', 'i', 'i', 'i', 1, 2, 3, 4, 5, 6, (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), 1, 2, 3, 4, 5, 6, (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)] 

In [85]:
#extend operation can also be use to add multiple items and list 
l2.extend(['oggy','cockroach'])
print(l2,end=" ")

['parul', 'rahul', 'tanya', 'romania', 'peraie', 'caribean', 5, 7, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'oggy', 'cockroach'] 

In [86]:
l2.extend([l1,'manya'])

In [87]:
print(l2,end=" ")

['parul', 'rahul', 'tanya', 'romania', 'peraie', 'caribean', 5, 7, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'oggy', 'cockroach', ['ram', 'sita', 34.4, 22, [[1, 4, 67, 89, 'list', 'tomato', 'brinjal']], ['rohan', 'anaya'], 3, 'parul', 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', 0, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 3, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], 'parul', [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], (5, 6), 1, 2, 3, 4, 5, 6, 'i', 'i', 'i', 'i', 'i', 'i', 1, 2, 3, 4, 5, 6, (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), 1, 2, 3, 4, 5, 6, (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], 'manya'] 

In [89]:
l3=['raman',3,3,l]
l3.extend([l3,'extend'])
print(l3,end=" ")

['raman', 3, 3, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], [...], 'extend'] 

In [90]:
#removing element from list
#use to remove the eleemnt from list
l3.remove(3)
print(l3,end=" ")#removing the element 3 d=from yhe list

['raman', 3, [1, 4, 67, 89, 'list', 'tomato', 'brinjal'], [...], 'extend'] 

In [2]:
# for printing zeros array
import numpy as np
t=np.zeros(20)#single d array of zeroes
t

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [3]:
#for printing two dimensional arrays of zeroes
t=np.zeros([5,5])
t

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
#for printing array of ones in one dimensional
t=np.ones(5)
t

array([1., 1., 1., 1., 1.])

In [5]:
#for printing 2-D arrays of 1's'
t=np.ones([5,5])
t

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# for defining  1-d arrays method 1
t1=np.array([22,44,55,'manya'])
t1

array(['22', '44', '55', 'manya'], dtype='<U11')

In [7]:
#method 2
l1=['rose','jack','roman']
t2=np.array(l1)
t2

array(['rose', 'jack', 'roman'], dtype='<U5')

In [9]:
#for definig 2-d array in python
t1=np.array([[22,33,44],[44,66,99],['rose','jack','raven'],l1])
t1

array([['22', '33', '44'],
       ['44', '66', '99'],
       ['rose', 'jack', 'raven'],
       ['rose', 'jack', 'roman']], dtype='<U11')

In [10]:
#method 2
#arange function gives a range b/w no.'s if written 0-,12 then array of 0,11'
t2=np.arange(0,12)
t2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
#reshape function - it formmatrix or array of no. of element in specific manner
t2=np.arange(0,12).reshape(3,4)#here are 12 element so can rearrange in 3*4 or 4*3 matrix
t2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
#3-D arrange or reshapeof matrix
y2=np.arange(1,13).reshape(2,2,3)#means 2*3 matrixand front 2 means two times 2*3 matrix
y2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
#linspace means no of element you want b/w any range
#i.e linapace (0,10,2) means two element from 0,10 range and at difference of 10
t2=np.linspace(0,10,2)    #another array defining method
t2      


array([ 0., 10.])

In [20]:
print(np.linspace(0,10,92))#no. of 92 elements print b/w 0,10 range

[ 0.          0.10989011  0.21978022  0.32967033  0.43956044  0.54945055
  0.65934066  0.76923077  0.87912088  0.98901099  1.0989011   1.20879121
  1.31868132  1.42857143  1.53846154  1.64835165  1.75824176  1.86813187
  1.97802198  2.08791209  2.1978022   2.30769231  2.41758242  2.52747253
  2.63736264  2.74725275  2.85714286  2.96703297  3.07692308  3.18681319
  3.2967033   3.40659341  3.51648352  3.62637363  3.73626374  3.84615385
  3.95604396  4.06593407  4.17582418  4.28571429  4.3956044   4.50549451
  4.61538462  4.72527473  4.83516484  4.94505495  5.05494505  5.16483516
  5.27472527  5.38461538  5.49450549  5.6043956   5.71428571  5.82417582
  5.93406593  6.04395604  6.15384615  6.26373626  6.37362637  6.48351648
  6.59340659  6.7032967   6.81318681  6.92307692  7.03296703  7.14285714
  7.25274725  7.36263736  7.47252747  7.58241758  7.69230769  7.8021978
  7.91208791  8.02197802  8.13186813  8.24175824  8.35164835  8.46153846
  8.57142857  8.68131868  8.79120879  8.9010989   9.

In [21]:
#print a range of no.'s b/w two number at with gap of particular number
#here print no.s b/w 0 and 10 with gap of 2'
t3=np.arange(0,10,2)
t3

array([0, 2, 4, 6, 8])

In [22]:
# idenrtity matrix
t=np.eye(2,2)#represent the order of identity maytreix
t

array([[1., 0.],
       [0., 1.]])

In [25]:
t=np.eye(4,4)
t


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
t1=np.eye(1,1)
t1

array([[1.]])